### ISSUE TITLE
Implement settings splash notice

### ISSUE THREAD

**Issue by postphotos** [Automattic/amp-wp#1381]
**As a new user of the AMP WP plugin, I need a splash screen that helps with understanding of what the plugin does, what settings do and how to solve AMP errors.**

- [x] AC1: WORDING - Identify or write copy that helps explain what settings do, what next steps are past activation (related #1366).  
- [ ] AC2: DESIGN - Finalize design (related #1288) of what this should look like in a high fidelity fashion with all art assets prepared for the plugin. 
   - [ ] Link to the product site, where a user would be able to understand what the plugin does, how AMP works and why they should use this tool.
- [ ] AC3: INTERFACE - On the settings page, implement the ability to have a dismissible splash "panel" that sits above the toggles.
- [ ] AC4: Implement new settings toggle design (related #1288) from AC2.  
- [ ] AC5: Combine AC1, AC2 and AC3, AC4 work in visual styles and functionality.

cc: @jwold @jillchu

**Comment by jwold** [comment]
@postphotos thanks for adding definition to this. This is really helpful for moving forward. When should we plan to have this ready for development to pickup?

**Comment by kienstra** [comment]
**Request For Design**

Hi @postphotos,
Thanks for working on this. 

Is there someone that can work on the design from AC2 and AC3? It would really help to have this ready for development soon.

Thanks, Leo!

**Comment by postphotos** [comment]
Hi @kienstra! We have two different designs in progress (@jwold @jillchu) a couple of questions right now around how much effort we can place toward settings. 

There's a chance we may minimize the effort here to focus on what is easiest to release for `v1.0-RC1`, I'll let you know when I know more. 😄

**Comment by kienstra** [comment]
Thanks, @postphotos!

**Comment by kienstra** [comment]
**In Progress**

Though we can be flexible in changing the copy of the notice, I'm beginning development on this.

**Comment by kienstra** [comment]
**PR Has Placeholder Message**

PR #1442 has a placeholder message, which can be dismissed. Once it's dismissed, it won't display again for that user.

**Comment by postphotos** [comment]
Hi @kienstra and @jwold  - for AC1, the final proposed wording we have is as follows:

```Markdown
# Welcome to the AMP for WordPress plugin v1.0
Thank you for installing! Bring the speed and features of the open source AMP project to your site, the WordPress way, complete with the tools to support content authoring and website development. 

## What's New
From granular controls that help you create AMP content, to Core Gutenberg support, to a sanitizer that only shows visitors error-free pages, to a full error workflow for developers, this v1.0 release makes it easier than ever to bring a rich, performant experience to your WordPress site via AMP HTML.
```

**Comment by kienstra** [comment]
Thanks, @postphotos! That looks good.

**Comment by jwold** [comment]
@kienstra

I'd like to suggest the following changes to the welcome banner (note that I changed a few lines of text as well). What do you think?

<img width="1051" alt="illustration" src="https://user-images.githubusercontent.com/3411173/45794331-fe02d380-bc4a-11e8-9031-8f9c0916e7e8.png">

And the icon:

[icon.svg.zip](https://github.com/Automattic/amp-wp/files/2399502/icon.svg.zip)


cc @postphotos

**Comment by jwold** [comment]
@ThierryA, @amedina, @postphotos:

We had a meeting this morning to chat about changes to this notice, anything we're missing? Or does this look good? Thanks!

<img width="1050" alt="notice" src="https://user-images.githubusercontent.com/3411173/45843870-947bd700-bcd5-11e8-8c43-b35047ddddcc.png">

[icon_r2.svg.zip](https://github.com/Automattic/amp-wp/files/2402900/icon_r2.svg.zip)

And the text from the notification:

> **Welcome to AMP for WordPress**

> Bring the speed and features of the open source AMP project to your site, complete with the tools to support content authoring and website development. 

> From granular controls that help you create AMP content, to Core Gutenberg support, to a sanitizer that only shows visitors error-free pages, to a full error workflow for developers, this release enables rich, performant experiences for your WordPress site.

**Comment by kienstra** [comment]
Hi @jwold,
Thanks, this looks really good. 

Where would the 'Learn More' link go to?

**Comment by jwold** [comment]
I was thinking the learn more link would go to the Product Site

**Comment by postphotos** [comment]
@kienstra as product site won't be ready until likely after RC, we should (for `v1.0-beta4` purposes) not include it. 😄 

I broke out the subtask into its own AC, and as your work is ready I'd keep this issue open util that link is usable.

**Comment by jacobschweitzer** [comment]
I've opened [PR #1470](https://github.com/Automattic/amp-wp/pull/1470) for this. Could you take a look @westonruter ? 

Here is a screenshot of the final result @jwold  @postphotos : 

<img width="1256" alt="screen shot 2018-09-26 at 4 06 31 pm" src="https://user-images.githubusercontent.com/3016425/46103240-b8905a00-c1a6-11e8-9a60-aca6857add49.png">

**Comment by kienstra** [comment]
**Request For Testing**

Hi @csossi,
Could you please test the notice that appears [here](https://paired-ampconfdemo.pantheonsite.io/wp-admin/admin.php?page=amp-options) against the [design and copy](https://github.com/Automattic/amp-wp/issues/1381#issuecomment-423315156)?

<img width="1306" alt="splash-notice" src="https://user-images.githubusercontent.com/4063887/46163975-542ad480-c252-11e8-8ac9-42b949d6931f.png">

**Comment by csossi** [comment]
verified in QA

**Comment by kienstra** [comment]
Yes, thanks for closing it.
