### ISSUE TITLE
Fix the outline box and block selector to make it clearer what block has been selected. 

### ISSUE THREAD

**Issue by alcurrie** [Automattic/amp-wp#1524]
**As a AMP Stories author, I want the interface for the outline box and the block selector improved so that I can easily understand what block has been selected**
 - [ ]  _AC 1:_ Fix/Improve  the interface for the outline box and the block selector to make it clearer what block has been selected
    - [ ]  _AC 2:_ Add Blue outline with highlight around selected block
          **Selected Block** (ie text block) 
![selectedblock](https://user-images.githubusercontent.com/18579988/48522822-1278dc00-e848-11e8-9bd9-5ceb8c19de61.png)
 (_NB: forward/back arrows show for selected block. See_ #1564) 
    - [ ]  _AC 3:_Add Blue outline what will show around Layer when the layer is selected *The blue line around the paragraph should not be displaying when the page is selected - mock up is incorrect.
     **Selected Layer**  (ie thirds layer) 
![selectedlayer](https://user-images.githubusercontent.com/18579988/48522850-1c9ada80-e848-11e8-915b-14d4a2e24f9b.png)
 (_NB: forward/back arrows show for selected Layer. See_ #1564) 
    - [ ]  _AC 4:_Add Blue outline what will show around Story page when the story page is selected  (_NB: forward/back arrows show  for selected story page._ See #1564) 
    - [ ]  _AC 5:_  Add Blur to all elements below the layer that contains the selected element.  For additional clarity for the user, as well as visually highlighting the selected element on a layer,  all elements on the layer below will be blurred, and any elements in the layers above the selected element will be hidden. See discussion in #1564 
    - [ ]  _AC 6:_  Add White shadow below placeholder text so that placeholder text is more visible  on darker backgrounds
    - [ ] _AC 7:_ Ensure that there is a visible hover for block elements (similar to what is default for Gutenberg) and that goes around the whole element. 
 - [ ]  _AC 7:_ The interface change should be aligned with and work well with the other related interface changes.  
    - [x]  Layer inserter will be moved to above the block navigation (Resolved in #1563)  
    - [x]  Forward/back arrows show for selected Block, Layer or AMP story (Resolved in #1564) 
    - [ ]  Highlight (bold) element selected in Block navigation. (Resolved in #1563)  
    - [ ]  Blur all blocks/layers below not selected and hide layers above (Resolved in #1524)

**Comment by jwold** [comment]
This one needs investigation to make sure the issue still exists with the new Gutenberg update, and posting some screenshots or a video showing what the problem is.

**Comment by miina** [comment]
Note for dev: Development is blocked by UX/design work.

**Comment by jwold** [comment]
In chatting with @alcurrie today here are a few issues we found:

1. https://v.usetapes.com/9JGJJu3uE7
2. https://d.pr/i/IG8PY3

There may be additional items to investigate, and there may be cross referenced items already called out in other issues, we'll circle back and validate what's unique to this ticket, and what might need to be added.

**Comment by jwold** [comment]
Discussion from Weston: Need to solve the problem of layer + paragraph on top of layer + paragraph. Maybe 50% background layer.

**Comment by cathibosco** [comment]
Will the blur effect as demonstrated on 1560 be a valid option?

It can be seen in Instagram on page loading.
![0f4c4440-44de-447a-afc6-2d45b4067dc0](https://user-images.githubusercontent.com/4819761/48235888-da782180-e38d-11e8-8cba-c18e7b5c6972.jpeg)


https://canddstudios.d.pr/NZvofY

**Comment by cathibosco** [comment]
Here is a visual suggestion for highlighting the element we are actively editing.... 
Outline with a shadow for displaying on light or dark backgrounds....

![amp-story-page-1-layer outlined](https://user-images.githubusercontent.com/4819761/48274219-d2ad9100-e410-11e8-9cc2-f19edc01505d.png)

**Comment by cathibosco** [comment]
AC2 We are moving the selector above the Page 1 editor so that should help resolve any overlapping with editing... 
(if I am understanding these AC's correctly)

**Comment by mehigh** [comment]
On making the text visible even on top of dark backgrounds (with black text) I've found the best results with using multiple text shadows, like this:
http://cloud.urldocs.com/c0f19d803ace
This shows an extreme case where the background has both light & dark shades. 
And here's the same effect on top of a light gray color I inserted just for testing purposes - http://cloud.urldocs.com/ab49a834d832 - the text is still fully legible.

Here you can also see the blue outline I've added around it:
http://cloud.urldocs.com/1a2dd23af774
Out of the box Gutenberg ads this blue border when hovering an element, gray for selected and gone when typing.
I've made it so the blue stays while the element is selected and even while typing. 
The border accompanies the white shadow of the black text in the rich editors in there.

**Comment by mehigh** [comment]
Addressed AC2 and AC6 in the referenced PR ^.

**Comment by mehigh** [comment]
@miina AC 3:_Add Blue outline what will show around Layer when the layer is selected
Selected Layer (ie thirds layer)_ would work if we keep the is-selected class going or handling a similar class added by ourselves when we click one of the layers.

**Comment by miina** [comment]
@mehigh There should be a default selector for it and we should actually already have a border, it's just not very visible:
![screen shot 2018-11-20 at 2 14 15 pm](https://user-images.githubusercontent.com/3294597/48790681-ae826780-ecce-11e8-969b-e830c8af8c2a.png)

Here you can see the `is-selected`:
![screen shot 2018-11-20 at 2 13 43 pm](https://user-images.githubusercontent.com/3294597/48790682-ae826780-ecce-11e8-8025-56d3dcc6dd42.png)

Do you think that is sufficient to add the outline for the selected layer?

**Comment by mehigh** [comment]
AC1's children:

AC2 - Text block selected border - Fixed in PR #1629 ( http://cloud.urldocs.com/7ec491663479 ). 

AC3 - Layer selected border - Fixed in PR #1629 ( http://cloud.urldocs.com/7ec491663479 ). 

AC4 - Story page selected border - Updated it to the same darker blue which is more visible - Fixed in PR #1629 ( http://cloud.urldocs.com/fed062238ec2 )

AC5 - Fixed with the already merged PR - this is available now on staging. ( http://cloud.urldocs.com/7ec491663479 )

AC6 - White shadow to text - Fixed in PR #1629 ( http://cloud.urldocs.com/7ec491663479 ). 

AC7 - The hover is visible on the other text blocks - Fixed in PR #1629 http://cloud.urldocs.com/c185bb2c62b4

So far AC2 (first level AC) is covered, as neither of these changes create any negative consequences with the other related work handled in other tickets. 
Passing it on to code review and then it should be ready for QA.

**Comment by miina** [comment]
@mehigh Assigned you back for now (for the last change of removing blue outline from selected parent).

**Comment by mehigh** [comment]
Handled the last feedback of not applying the blue border to the parents of the selected item and merged the PR. Moving this on to QA.

**Comment by alcurrie** [comment]
Confirmed working as described in the AC:    https://cl.ly/6f22f357812f
