### ISSUE TITLE
Improve block placeholder styles to make it easier to see an empty element when it is added in a layer on top of another.

### ISSUE THREAD

**Issue by alcurrie** [Automattic/amp-wp#1560]
**As an AMP Story author, I'd like improved styling/interface  so that it's easier to see an empty element when it is added in a layer on top of another layer.**
 - [x] _AC 1:_ Improve block placeholder styles to make it easier to see an empty element when it is added in a layer on top of another.  
      - [ ]  Resolved in #1563  AC-5 and AC-6 (block navigation), AC-7 and AC-8 (blue line selector), and  in #1524  (blur layers below) 
  - [x]  _AC 2:_ Move layer inserter so that layer inserter is never over top of the Story page. 
      - [x]  Instead of  having the layer inserter overlapping the top of the AMP stories interface, move the (+) Add Layer to just above the block navigation and can click/tap on the (+) Add Layer interface to add a new layer, as shown in these mockups  (This is resolved in #1563 AC-10 and 11):
![moveaddlayertoaboveblocknav](https://user-images.githubusercontent.com/18579988/48555585-acc03a80-e8af-11e8-9c31-4ddea354a072.png) 
![addlayerinterface](https://user-images.githubusercontent.com/18579988/48556420-e5611380-e8b1-11e8-9162-961b1bed6328.png)
 - [x] _AC 3:_  Resolve the issue shown here, where it is hard for a user to select a paragraph of text with an image next to it: https://v.usetapes.com/LTwvB612Ob 
      - [x]  Issue will be resolved by the blur effect applying to all blocks not on the current layer, and the implementation of the blue border selector, and the block navigation interface.  Resolved in #1563  AC-5 and AC-6 (block navigation), AC-7 and AC-8 (blue line selector), and  in #1524  (blur layers below) 
 
Related to #1563  #1564  #1541 #1559

**Comment by jwold** [comment]
If we can start by just adding margin between elements, it should solve usability by spacing all elements out a tad. We'll let the dev team take a stab at this and see if it works.

**Comment by jwold** [comment]
There's a further issue, which may be for this ticket, where a layer has a paragraph, and another layer has a paragraph, and they're right on top of each other; in that case it's very hard to see the paragraph of text from one layer to the next, since they overlap. 

One suggestion was to put a 50% white opacity between layers to make them less visible.

**Comment by cathibosco** [comment]
I mocked up an unattractive graphic to show what 50% opacity will do for us. It does help, but it seems like it is not enough. I am not sure how this would be done in terms of development but...

I included the 50% white opacity layer between the top and lower layer and then I also added a blur effect on the lower layer which in combination with the 50% white opacity made the top layer much better to work on... here is a .gif  Does this seem possible? :)

This blur effect maintains the lower layer colors preserved for ease of editing with different color fonts.


![screen capture on 2018-11-06 at 16-20-03](https://user-images.githubusercontent.com/4819761/48094859-436e6680-e1e1-11e8-8d2f-d6d695684f47.gif)

**Comment by cathibosco** [comment]
Here is a better visual of the blur effect...
I see this is used in Instagram on load.... as a placeholder and as the page loads..
It would be great if it was a valid option. Please take a look at the gif

https://canddstudios.d.pr/NZvofY

Here is a screenshot of Insta blur:
![img_2200](https://user-images.githubusercontent.com/4819761/48144638-428c1200-e27f-11e8-9993-995c482d6362.PNG)

**Comment by cathibosco** [comment]
@miina Do you think the blur effect is viable? For ac2?

**Comment by miina** [comment]
@cathibosco Looks like blur possibly together with opacity 50% background could work well.

We could try it out and then see how it looks like! And then think of alternatives if it still feels like not clear enough. Thoughts?

**Comment by alcurrie** [comment]
@miina  - I've updated the AC here and assumed that the all the items here are covered in other issues as referenced. However, it may be easier from a development perspective to leave the move of the add layer interface change in this issue and remove it from the AC for #1563  Ideally, we could close issues that are covered off in 'other' issues, to clear the board, but there might be a reason, to keep the functionality separated.  Thoughts?

**Comment by alcurrie** [comment]
Thanks @miina   Per discussion above, we are closing this as the Acceptance criteria for this issue will be resolved by #1563 and #1524 

cc. @westonruter
