### ISSUE TITLE
[Epic] Updating labels

### ISSUE THREAD

**Issue by kmyram** [Automattic/amp-wp#5907]
Define types of issues as labels (pseudo-types) to better suit the different variants of work we do.

In this epic we track the separate tasks but with a finite range of updates, additions and changes to the list of labels we have already. Since the functionality is limited this is how we can distinguish among the issues on board and in backlog and we use the labels not only for quick tagging but for categorization and tracking.

- [ ] Determine behaviour when deleting, changing and updating labels (task)
- [ ] Groom the list of existing labels (task)
- [ ] Order labels by category ('pseudo-types') and maintain documentation of these (ie. differ on static and dynamic) (task)
- [ ] Determine way to automate labels and description (over time) (task)
- [ ] How to track by label(s) (task)

Expected outcome is documentation on the wiki.
