### ISSUE TITLE
[Epic] Managing epics

### ISSUE THREAD

**Issue by kmyram** [Automattic/amp-wp#5909]
Most of the functionality in the roadmap can be described as epics - and we are managing epics in issues at the moment. We'll continue to do that but add some manual effort to track progress, capture information and manage it all in and around these issues.

Tasks are..

- [ ] Put epics into issues (by workstream)
- [ ] Compile list with complementary information in wiki
- [ ] Add categorization (labelling) to epics
