### ISSUE TITLE
Update spec to include fetchpriority support

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#7601]
### Feature Description

- [x] Update spec once `fetchpriority` support has landed: https://github.com/ampproject/amphtml/issues/38715 This is done with #7615.
- [x] Remove obsolete Bento support as noted in https://github.com/ampproject/amp-wp/pull/7597#issuecomment-1664245668
- [x] Make sure that the image sanitizer passes through `fetchpriority`.
- [x] Update amp-toolbox-php to dev-master util changes tested and full 11.3 release is made.

**Comment by westonruter** [comment]
> * Update spec once `fetchpriority` support has landed: [AMP Validator: Allow attribute 'fetchpriority' for link tag amphtml#38715](https://github.com/ampproject/amphtml/issues/38715)

This has landed in https://github.com/ampproject/amphtml/commit/49ee0db2df07f23511a4525ec116ec60c321d3ea as part of https://github.com/ampproject/amphtml/releases/tag/2309011827000

**Comment by thelovekesh** [comment]
Thanks, for the update @westonruter, I will start working on it.

**Comment by westonruter** [comment]
Looks like the spec update is live, but note it is only for `img` and not `amp-img`:

`img` | `amp-img`
------|----------
![image](https://github.com/ampproject/amp-wp/assets/134745/8de9d12d-e0f8-47ab-be89-69610671329f) | ![image](https://github.com/ampproject/amp-wp/assets/134745/24abcd23-736d-4d21-85d9-ac88fd7f796a)

This makes sense because `amp-img` is lazy-loaded by the runtime, so it doesn't make sense for the attribute to be on it. The attribute also works for SSR'ed `img`, which is just what we need:

![image](https://github.com/ampproject/amp-wp/assets/134745/d41598e1-8ea8-4888-882f-4e005af6020c)

Lastly, it also works in the `noscript > img` fallback.

So what we need to do is this:

1. If `fetchpriority=high` is on an `img` and the image sanitizer is configured to convert to `amp-img`, we'll need to remove this attribute from the `amp-img` since it isn't allowed there. But we will need to remember it was there originally. This could be done with a new data attribute, or we could automatically add the `data-hero` attribute which the AMP Optimizer uses as a signal to SSR. Another option is the `data-hero-candidate` which the AMP plugin uses as a hint for what could be a hero.
2. Retain `fetchpriority=high` on the `noscript > img` fallback.
3. Update AMP Toolbox to also _always_ SSR any `amp-img` that originally had a `fetchpriority=high` on the `img`. This would be to update the [`OptimizeHeroImages`](https://github.com/ampproject/amp-toolbox-php/blob/main/src/Optimizer/Transformer/OptimizeHeroImages.php) transformer so that `findHeroImages` always returns an `amp-img` which had `fetchpriority=high`. Notice also how AMP Optimizer will [preserve](https://github.com/ampproject/amp-toolbox-php/blob/b9e2df167ae70de8473f6c15f1d1f1662e71b9a8/src/Optimizer/Transformer/OptimizeHeroImages.php#L564-L567) the `loading` attribute from the `amp-img > noscript > img` callback.

**Comment by westonruter** [comment]
I can see that the first todo item is completed with the spec update in #7615, but it's not yet merged.

**Comment by westonruter** [comment]
Workaround plugin code to suppress the error:

```php
add_filter(
	'amp_validation_error_sanitized',
	static function ( $sanitized, $error ) {
		if (
			'DISALLOWED_ATTR' === $error['code'] &&
			'fetchpriority' === $error['node_name']
		) {
			$sanitized = true;
		}
		return $sanitized;
	},
	10,
	2
);
```

**Comment by westonruter** [comment]
@thelovekesh Just added this todo:

> Update amp-toolbox-php to dev-master util changes tested and full 11.3 release is made.

This can be done as part of the PR that makes sure that `fetchpriority` is preserved on the `img` when converted to `amp-img` (or when native `img` is enabled). Actually I expect it is already passed through, so there may not be any changes other than adding some `AMP_Img_Sanitizer` tests to verify that the expected behavior is happening.

**Comment by thelovekesh** [comment]
Yes, only one change is required in `AMP_Img_Sanitizer` to prevent adding `fetchpriority` attribute to the `amp-img`.

**Comment by pavanpatil1** [comment]
QA Passed ✅ 

The FetchPriority attribute is visible within the image and remains present when the native HTML image tag is enabled.


**Task 1:** 

The fetchpriority is added inside the image tag - 

https://github.com/ampproject/amp-wp/blob/66b86680f6f1db819be2a0b37f5d5dee64cac201/includes/sanitizers/class-amp-allowed-tags-generated.php#L11623C10-L11623C10

**Task 2:** 

Cross-checked it and it is working fine. It is not supported now. 

<details><summary>Details</summary>

![image](https://github.com/ampproject/amp-wp/assets/44057535/7be5bffa-8d12-433d-b5ca-0b5a7025bd9a)

</details> 




**Task 3:** 

With the native HTML image tag enabled: 

<details><summary>Details</summary>

![image](https://github.com/ampproject/amp-wp/assets/44057535/b5e8fcf0-6b6c-4754-98f5-29f4eb7ce68b)

</details> 



With the amp-img tag: 

<details><summary>Details</summary>

![image](https://github.com/ampproject/amp-wp/assets/44057535/ea8f0aff-42aa-4fa7-b9dc-05593862f379)

</details> 

**Task 4:** 

The amp-toolbox-php is updated to dev-mode: 

https://github.com/ampproject/amp-wp/blob/66b86680f6f1db819be2a0b37f5d5dee64cac201/composer.json#L17C4-L17C42
